using System.Globalization;
using System.Windows;

namespace TopSolid.Automation.AI.Studio.Localization;

/// <summary>Studio-owned interface text only. Names, tool identifiers, receipts and user content are never translated.</summary>
public static class StudioStrings
{
    private sealed record Entry(string Key, string English, string Korean);
    private static readonly Entry[] Entries =
    [
        new("Preview.Title", "3D preview", "3D 미리보기"),
        new("Preview.Current", "Current document", "현재 문서"),
        new("Preview.Proposed", "Proposed geometry", "생성할 형상"),
        new("Preview.DocumentContext", "Document context", "문서 전체 형상"),
        new("Preview.ProposedHint", "Requested geometry · 0.05 mm / 5° · created after approval.", "요청한 형상 · 0.05 mm / 5° · 승인 후 생성합니다."),
        new("Preview.ContextHint", "Current geometry · full document view.", "현재 형상 · 문서 전체 보기."),
        new("Preview.Precision", "Preview tolerance: 0.05 mm / 5°", "미리보기 공차: 0.05 mm / 5°"),
        new("Preview.NativePrecision", "Preview uses the document's display tolerance.", "문서의 시각화 공차를 사용합니다."),
        new("Preview.MouseHint", "Orbit: Ctrl + right drag or wheel-button drag · Pan: right drag · Zoom: scroll", "회전: Ctrl+오른쪽 또는 휠 버튼 드래그 · 이동: 오른쪽 드래그 · 확대/축소: 휠"),
        new("Preview.Controls", "Orbit: Ctrl + right drag or wheel-button drag. Pan: right drag. Zoom: scroll. Arrow keys rotate; +/− zoom; F fits; Home resets the view.", "회전: Ctrl+오른쪽 또는 휠 버튼 드래그. 이동: 오른쪽 드래그. 확대/축소: 휠. 화살표: 회전, +/−: 확대/축소, F: 전체 보기, Home: 기본 방향."),
        new("Preview.Refresh", "Refresh preview", "미리보기 새로 고침"),
        new("Preview.Orbit", "Orbit", "회전"),
        new("Preview.Pan", "Pan", "이동"),
        new("Preview.Fit", "Fit model (F)", "전체 보기 (F)"),
        new("Preview.Edges", "Show / hide edges", "모서리 표시 / 숨기기"),
        new("Preview.Loading", "Loading 3D preview…", "3D 미리보기 불러오는 중…"),
        new("Preview.Choose", "Select an item to preview its document.", "항목을 선택하면 문서 형상을 표시합니다."),
        new("Preview.notLoaded", "Open this document in TopSolid to preview it.", "미리 보려면 TopSolid에서 이 문서를 열어 주세요."),
        new("Preview.unsupported", "No 3D preview is available for this document.", "이 문서는 3D 미리보기를 지원하지 않습니다."),
        new("Preview.tooLarge", "This model is too large for a dialog preview. Review it in TopSolid.", "대화 상자에서 미리 보기에는 큰 모델입니다. TopSolid에서 확인해 주세요."),
        new("Preview.changed", "The document changed while loading. Refresh the preview.", "불러오는 동안 문서가 변경되었습니다. 미리보기를 새로 고침해 주세요."),
        new("Preview.unavailable", "Preview unavailable. You can still review the details below.", "미리보기를 표시할 수 없습니다. 변경 사항은 계속 확인할 수 있습니다."),
        new("Preview.View.iso", "Isometric", "등각 보기"),
        new("Preview.View.top", "Top", "위에서"),
        new("Preview.View.front", "Front", "앞에서"),
        new("Preview.View.right", "Right", "오른쪽에서"),
        new("Activity.Question", "Waiting for your answer", "답변을 기다리는 중"),
        new("Question.Title", "Your input", "선택 및 입력"),
        new("Question.ChooseProject", "Which project should be used?", "어떤 프로젝트를 사용할까요?"),
        new("Question.SelectHint", "Choose an item to continue.", "계속하려면 항목을 선택하세요."),
        new("Question.MultipleHint", "Choose one or more items to continue.", "계속하려면 하나 이상의 항목을 선택하세요."),
        new("Question.InputHint", "Enter a value to continue.", "계속하려면 값을 입력하세요."),
        new("Question.Search", "Search by name or location", "이름 또는 위치로 검색"),
        new("Question.ClearSelection", "Clear selection", "선택 해제"),
        new("Question.NoMatches", "No matching items", "일치하는 항목이 없습니다"),
        new("Question.Count", "{0} of {1} loaded items · {2} selected", "불러온 {1}개 중 {0}개 표시 · {2}개 선택"),
        new("Question.Cancel", "Cancel", "취소"),
        new("Question.Continue", "Continue", "계속"),
        new("Question.Unnamed", "Unnamed {0} · {1}", "이름 없는 {0} · {1}"),
        new("Question.SelectRequired", "Select an item to continue.", "계속하려면 항목을 선택하세요."),
        new("Question.TextRequired", "Enter text (up to 4,000 characters).", "텍스트를 입력하세요 (최대 4,000자)."),
        new("Question.NumberRequired", "Enter a valid number without thousands separators.", "천 단위 구분 기호 없이 올바른 숫자를 입력하세요."),
        new("Question.IntegerRequired", "Enter a whole number between −2,147,483,648 and 2,147,483,647.", "−2,147,483,648에서 2,147,483,647 사이의 정수를 입력하세요."),
        new("Question.OutOfRange", "Enter a value within the displayed limits.", "표시된 범위 안의 값을 입력하세요."),
        new("Question.SelectionTooLarge", "Select fewer items to continue.", "계속하려면 선택한 항목 수를 줄이세요."),
        new("Question.Minimum", "Minimum: {0}", "최솟값: {0}"),
        new("Question.Maximum", "Maximum: {0}", "최댓값: {0}"),
        new("Question.ColorRequired", "Choose a color or enter #RRGGBB / RGB values from 0 to 255.", "색상을 선택하거나 #RRGGBB / 0~255의 RGB 값을 입력하세요."),
        new("Question.ChooseImage", "Choose image…", "이미지 선택…"),
        new("Question.ImageHint", "PNG or JPEG · up to 5 MB. Continue sends this image to your selected AI service.", "PNG 또는 JPEG · 최대 5 MB. 계속을 누르면 선택한 AI 서비스에 이 이미지를 보냅니다."),
        new("Question.ImageRequired", "Choose an image to continue.", "계속하려면 이미지를 선택하세요."),
        new("Question.ImageFilter", "Images (PNG, JPEG)|*.png;*.jpg;*.jpeg", "이미지 (PNG, JPEG)|*.png;*.jpg;*.jpeg"),
        new("Question.LoadingImage", "Loading image…", "이미지 불러오는 중…"),
        new("Question.Cancelled", "Question cancelled. No changes were made.", "입력을 취소했습니다. 변경하지 않았습니다."),
        new("Question.CancelledAfterChange", "Question cancelled. The workflow stopped; earlier action receipts remain in the chat.", "입력을 취소하여 작업을 중지했습니다. 이전 작업 결과는 채팅에 남아 있습니다."),
        new("Question.Kind.option", "Option", "항목"),
        new("Question.Kind.project", "Project", "프로젝트"),
        new("Question.Kind.library", "Library", "라이브러리"),
        new("Question.Kind.document", "Document", "문서"),
        new("Question.Kind.parameter", "Parameter", "파라미터"),
        new("Question.Kind.operation", "Operation", "작업"),
        new("Question.Kind.machine", "Machine", "기계"),
        new("Question.Kind.camParameter", "CAM parameter", "가공 파라미터"),
        new("Question.Kind.element", "Element", "요소"),
        new("Question.Kind.edge", "Edge", "모서리"),
        new("Question.Kind.point", "Point", "점"),
        new("Question.Kind.curve", "Curve", "곡선"),
        new("Question.Kind.surface", "Surface", "곡면"),
        new("Question.Kind.shape", "Shape", "형상"),
        new("Question.Kind.text", "Text", "텍스트"),
        new("Question.Kind.integer", "Whole number", "정수"),
        new("Question.Kind.decimal", "Number", "숫자"),
        new("Response.Item", "Item", "항목"),
        new("Response.UnnamedItem", "TopSolid item (name unavailable)", "TopSolid 항목 (이름 확인 불가)"),
        new("Response.Yes", "Yes", "예"),
        new("Response.No", "No", "아니요"),
        new("Nav.AiModel", "AI model", "AI 모델"),
        new("Nav.Appearance", "Appearance", "화면 모드"),
        new("Nav.Languages", "Languages", "언어"),
        new("Nav.Developer", "Developer", "개발자"),
        new("Nav.Chat", "Chat", "채팅"),
        new("Nav.Settings", "Settings", "설정"),
        new("Common.BackToChat", "Back to chat", "채팅으로 돌아가기"),
        new("Common.Save", "Save settings", "설정 저장"),
        new("Common.Cancel", "Cancel", "취소"),
        new("Common.Approve", "Approve", "승인"),
        new("Common.Refresh", "Refresh", "새로 고침"),
        new("Common.RefreshAll", "Refresh connections, models and TopSolid status", "연결, 모델 및 TopSolid 상태 새로 고침"),
        new("Common.Browse", "Browse…", "찾아보기…"),
        new("Common.Minimize", "Minimize", "최소화"),
        new("Common.Maximize", "Maximize or restore", "최대화 또는 복원"),
        new("Common.Close", "Close", "닫기"),
        new("Common.Remove", "Remove {0}", "{0} 제거"),
        new("Common.Saved", "Settings saved.", "설정을 저장했습니다."),
        new("Common.NotTested", "not tested", "확인하지 않음"),
        new("Common.Connected", "connected", "연결됨"),
        new("Common.Disconnected", "disconnected", "연결 끊김"),
        new("Common.Loading", "Loading…", "불러오는 중…"),
        new("Common.RefreshComplete", "Refresh complete", "새로 고침 완료"),
        new("Common.RefreshIncomplete", "Refresh incomplete", "새로 고침 미완료"),
        new("Common.ApiKeyRequired", "API key required", "API 키 필요"),
        new("Appearance.Light", "Light", "밝게"),
        new("Appearance.Dark", "Dark", "어둡게"),
        new("Appearance.System", "System", "Windows 설정"),
        new("Appearance.TopSolid", "TopSolid", "TopSolid 설정"),
        new("Appearance.Mode", "Color mode", "색상 모드"),
        new("Appearance.FollowTopSolid", "Follow TopSolid settings", "TopSolid 설정 따르기"),
        new("Appearance.Current", "Active theme: {0}", "현재 테마: {0}"),
        new("Appearance.TopSolidHint", "Follows the saved TopSolid color theme.", "저장된 TopSolid 색상 테마를 따릅니다."),
        new("Appearance.ClassicName", "TopSolid Classic", "TopSolid 클래식"),
        new("Appearance.DarkName", "TopSolid Dark", "TopSolid 다크"),
        new("Language.Interface", "Studio language", "Studio 표시 언어"),
        new("Language.Response", "AI response language", "AI 응답 언어"),
        new("Language.System", "System default", "시스템 언어"),
        new("Language.Auto", "Match my message", "메시지 언어에 맞춤"),
        new("Language.English", "English", "English (영어)"),
        new("Language.Korean", "한국어", "한국어"),
        new("Language.Japanese", "日本語", "日本語 (일본어)"),
        new("Language.Chinese", "中文", "中文 (중국어)"),
        new("Language.French", "Français", "Français (프랑스어)"),
        new("Language.German", "Deutsch", "Deutsch (독일어)"),
        new("Language.Spanish", "Español", "Español (스페인어)"),
        new("Language.InterfaceHint", "Changes menus, settings and Studio messages immediately.", "메뉴, 설정 및 Studio 메시지에 즉시 적용됩니다."),
        new("Language.ResponseHint", "Applies to new AI replies. Existing messages and TopSolid data keep their original text.", "새 AI 응답에 적용됩니다. 기존 메시지와 TopSolid 데이터는 원문을 유지합니다."),
        new("Settings.AiConfiguration", "AI configuration", "AI 구성"),
        new("Settings.Connection", "Connection", "연결 방식"),
        new("Settings.CloudApi", "Cloud API", "클라우드 API"),
        new("Settings.CloudService", "Cloud service", "클라우드 서비스"),
        new("Settings.ServerUrl", "Server URL", "서버 URL"),
        new("Settings.ApiKey", "API key", "API 키"),
        new("Settings.Model", "Model", "모델"),
        new("Settings.ListModels", "List models", "모델 목록 조회"),
        new("Settings.McpServer", "MCP server", "MCP 서버"),
        new("Settings.AiWait", "AI wait", "AI 응답 대기"),
        new("Settings.MoreThinking", "More thinking", "더 깊이 생각하기"),
        new("Settings.TimeoutUnit", "minutes per request", "분 / 요청"),
        new("Settings.EndpointHint", "Service URL is filled automatically. Choose Custom OpenAI-compatible to use another endpoint.", "서비스 URL은 자동으로 입력됩니다. 다른 주소를 사용하려면 Custom OpenAI-compatible을 선택하세요."),
        new("Settings.OpenAiKeyHint", "Use an OpenAI API key.", "OpenAI API 키를 사용하세요."),
        new("Settings.GeminiKeyHint", "Use a Gemini API key from Google AI Studio, not an OAuth token or an OpenAI key.", "Google AI Studio의 Gemini API 키를 사용하세요. OAuth 토큰 또는 OpenAI 키는 사용할 수 없습니다."),
        new("Settings.AnthropicKeyHint", "Use an Anthropic API key, not a Claude subscription login.", "Anthropic API 키를 사용하세요. Claude 구독 계정 로그인은 사용할 수 없습니다."),
        new("Settings.XaiKeyHint", "Use an xAI inference API key.", "xAI 추론 API 키를 사용하세요."),
        new("Settings.MetaKeyHint", "Use a Meta Model API key from dev.meta.ai, not a Groq key.", "dev.meta.ai의 Meta Model API 키를 사용하세요. Groq 키는 사용할 수 없습니다."),
        new("Settings.GroqKeyHint", "Meta Llama models hosted by Groq. Use a Groq API key, not a Meta key.", "Groq에서 제공하는 Meta Llama 모델입니다. Meta 키 대신 Groq API 키를 사용하세요."),
        new("Settings.MistralKeyHint", "Use a Mistral API key.", "Mistral API 키를 사용하세요."),
        new("Settings.DeepSeekKeyHint", "Use a DeepSeek API key.", "DeepSeek API 키를 사용하세요."),
        new("Settings.OpenRouterKeyHint", "Use an OpenRouter API key for models hosted through OpenRouter.", "OpenRouter에서 제공하는 모델에 사용할 OpenRouter API 키를 입력하세요."),
        new("Settings.CustomKeyHint", "Enter this endpoint's API key. Select a named service for its preset URL.", "이 서버의 API 키를 입력하세요. 미리 설정된 URL을 사용하려면 해당 서비스를 선택하세요."),
        new("Settings.InvalidService", "Choose a supported cloud service or Custom OpenAI-compatible.", "지원되는 클라우드 서비스 또는 Custom OpenAI-compatible을 선택하세요."),
        new("Chat.New", "New chat", "새 채팅"),
        new("Chat.Welcome", "What would you like to build?", "무엇을 만들어 볼까요?"),
        new("Chat.CurrentDocument", "Current document", "현재 문서"),
        new("Chat.ListProjects", "List projects", "프로젝트 목록"),
        new("Chat.CreateSketch", "Create a sketch", "스케치 만들기"),
        new("Chat.CurrentDocumentPrompt", "Read the active TopSolid document and summarize it.", "활성 TopSolid 문서를 읽고 요약해 주세요."),
        new("Chat.ListProjectsPrompt", "List all TopSolid projects.", "모든 TopSolid 프로젝트를 나열해 주세요."),
        new("Chat.CreateSketchPrompt", "Help me create a 2D sketch in the current document.", "현재 문서에 2D 스케치를 만들 수 있도록 도와주세요."),
        new("Chat.Placeholder", "Ask TopSolid…", "TopSolid에 물어보세요…"),
        new("Chat.Message", "Chat message", "채팅 메시지"),
        new("Chat.KeyboardHint", "Enter to send · Shift+Enter for a new line", "Enter로 보내기 · Shift+Enter로 줄 바꿈"),
        new("Chat.AddFiles", "Add files", "파일 첨부"),
        new("Chat.Send", "Send message", "메시지 보내기"),
        new("Chat.Cancel", "Cancel request", "요청 취소"),
        new("Chat.ModelHint", "Select a model · Configure or list models in Settings", "모델 선택 · 설정에서 모델 구성 또는 목록 조회"),
        new("Chat.Elapsed", "Elapsed {0}", "경과 시간 {0}"),
        new("Activity.Thinking", "Thinking…", "생각하는 중…"),
        new("Activity.Working", "Working…", "처리 중…"),
        new("Activity.TopSolid", "Working with TopSolid…", "TopSolid 작업 중…"),
        new("Activity.Parameters", "Working with parameters…", "파라미터 확인 및 처리 중…"),
        new("Activity.Operations", "Working with machining operations…", "가공 작업 확인 및 처리 중…"),
        new("Activity.PreparingResponse", "Preparing your response…", "응답을 정리하는 중…"),
        new("Activity.Approval", "Waiting for your approval", "변경 승인을 기다리는 중"),
        new("Activity.Applying", "Applying the approved change…", "승인된 변경 적용 중…"),
        new("Activity.Cancelling", "Cancelling…", "취소하는 중…"),
        new("Chat.Status", "MCP: {0} · Model: {1}", "MCP: {0} · 모델: {1}"),
        new("Chat.ConnectedTools", "connected ({0} tools)", "연결됨 (도구 {0}개)"),
        new("Chat.ListingModels", "listing models", "모델 목록 조회 중"),
        new("Chat.ListingFailed", "model listing failed", "모델 목록 조회 실패"),
        new("Chat.ModelResponseReceived", "response received", "응답 수신됨"),
        new("Chat.DirectMcp", "not used (direct MCP)", "사용 안 함 (MCP 직접 호출)"),
        new("Chat.CancelledStatus", "cancelled", "취소됨"),
        new("Chat.FailedStatus", "request failed", "요청 실패"),
        new("Chat.ModelsListed", "{0} models listed; inference not tested", "모델 {0}개 조회됨; 응답 생성은 확인하지 않음"),
        new("Chat.WaitingCommit", "Applying CAD change; waiting for commit/rollback", "CAD 변경 적용 중; 확정/되돌리기 대기 중"),
        new("Chat.ConfigurationChanged", "Configuration changed. Conversation preserved.", "구성이 변경되었습니다. 대화는 유지됩니다."),
        new("Chat.RequestCancelled", "Request cancelled.", "요청이 취소되었습니다."),
        new("Chat.Files", "Files: {0}", "첨부 파일: {0}"),
        new("Chat.EnterMessage", "Enter a message.", "메시지를 입력하세요."),
        new("Chat.MessageLimit", "Keep each message under 32,000 characters.", "메시지는 32,000자 이하로 입력하세요."),
        new("Chat.ToolCallLimit", "The model exceeded the 24-tool-call limit. Start a shorter request.", "모델이 도구 호출 한도 24회를 초과했습니다. 요청을 나누어 다시 실행하세요."),
        new("Chat.IncompleteList", "The model did not query all requested PDM lists. No unverified names are displayed. Try the request again.", "모델이 요청한 PDM 목록을 모두 조회하지 않았습니다. 확인되지 않은 이름은 표시하지 않습니다. 다시 요청하세요."),
        new("Chat.EmptyAnswer", "The model returned an empty answer.", "모델이 빈 응답을 반환했습니다."),
        new("Chat.InvalidToolCallId", "The model returned a missing or duplicate tool call ID.", "모델이 누락되거나 중복된 도구 호출 ID를 반환했습니다."),
        new("Chat.NoPreview", "MCP returned no change preview. No change was sent.", "MCP가 변경 미리보기를 반환하지 않았습니다. 변경 요청을 전송하지 않았습니다."),
        new("Chat.InvalidPreview", "Invalid change preview from MCP. No change was sent.", "MCP 변경 미리보기가 올바르지 않습니다. 변경 요청을 전송하지 않았습니다."),
        new("Chat.RoundLimit", "Stopped after 16 model rounds. Check the completed tool receipts before continuing this workflow in another message.", "모델 처리 16회 후 중단했습니다. 다음 메시지에서 이어서 작업하기 전에 완료된 도구 실행 결과를 확인하세요."),
        new("Chat.Declined", "Change declined. No changes were made.", "변경을 거절했습니다. 변경된 내용이 없습니다."),
        new("Chat.DeclinedAfterChanges", "This change was declined. The workflow stopped; earlier action receipts remain in the chat.", "이 변경을 거절하여 작업을 중단했습니다. 앞서 실행한 작업 결과는 채팅에 남아 있습니다."),
        new("Role.You", "You", "사용자"),
        new("Role.User", "User", "사용자"),
        new("Role.Assistant", "Assistant", "AI 도우미"),
        new("Role.System", "System", "시스템"),
        new("Role.TopSolidResult", "TopSolid result", "TopSolid 결과"),
        new("Permission.Label", "Permissions", "권한"),
        new("Permission.Ask", "Ask for approval", "승인 요청"),
        new("Permission.Auto", "Approve for me", "자동 승인"),
        new("Permission.Full", "Full access", "전체 접근"),
        new("Permission.AskHint", "Review the exact target and arguments before each TopSolid change. Read-only queries run directly.", "TopSolid를 변경하기 전에 정확한 대상과 인수를 검토합니다. 읽기 전용 조회는 바로 실행합니다."),
        new("Permission.AutoHint", "Automatically approve known reversible CAD edits. Ask before persistent PDM changes, saving, deletion, replacement, CAM execution, and unknown actions.", "검증된 되돌릴 수 있는 CAD 편집을 자동 승인합니다. PDM 영구 변경, 저장, 삭제, 교체, CAM 실행 및 미확인 작업 전에는 승인을 요청합니다."),
        new("Permission.FullHint", "Automatically approve known MCP actions, including persistent and destructive changes. MCP preparation, exact target validation, and cancellation still apply. Unknown actions require approval.", "영구 변경과 삭제를 포함한 검증된 MCP 작업을 자동 승인합니다. MCP 사전 준비, 정확한 대상 확인 및 취소 절차는 유지됩니다. 미확인 작업은 승인이 필요합니다."),
        new("Permission.AskShort", "Ask before each TopSolid change.", "TopSolid를 변경하기 전에 승인을 요청합니다."),
        new("Permission.AutoShort", "Automatically approve recognized reversible edits. Ask before saving, deleting, exporting, or unknown actions.", "검증된 되돌릴 수 있는 편집은 자동 승인합니다. 저장, 삭제, 내보내기 및 미확인 작업은 승인을 요청합니다."),
        new("Permission.FullShort", "Automatically approve validated TopSolid tool changes for this session.", "이 세션에서 검증된 TopSolid 도구 변경을 자동 승인합니다."),
        new("Attachment.Picker", "Add files to this message", "이 메시지에 파일 첨부"),
        new("Attachment.SupportedFiles", "Supported files", "지원되는 파일"),
        new("Attachment.Images", "Images (PNG, JPEG)", "이미지 (PNG, JPEG)"),
        new("Attachment.TextFiles", "Text and source files", "텍스트 및 소스 파일"),
        new("Attachment.Drop", "Drop files to attach", "파일을 놓아 첨부하세요"),
        new("Attachment.NextMessage", "Added to your next message", "다음 메시지에 첨부됩니다"),
        new("Attachment.ProviderHint", "Included with your next message to the selected AI provider.", "선택한 AI 제공자에게 보내는 다음 메시지에 포함됩니다."),
        new("Attachment.Unsupported", "Attach PNG/JPEG images or supported text/source files. PDF, Office, and native CAD files are not supported; export a screenshot or text first.", "PNG/JPEG 이미지 또는 지원되는 텍스트/소스 파일을 첨부하세요. PDF, Office 및 CAD 원본은 지원하지 않습니다. 먼저 스크린샷이나 텍스트로 내보내세요."),
        new("Attachment.Empty", "The selected file is empty.", "선택한 파일이 비어 있습니다."),
        new("Attachment.ImageLimit", "Keep each image under 5 MB.", "이미지당 5 MB 이하로 첨부하세요."),
        new("Attachment.TextSizeLimit", "Keep each text file under 48 KB and 12,000 characters.", "텍스트 파일은 각각 48 KB 및 12,000자 이하로 첨부하세요."),
        new("Attachment.Changed", "The selected file changed while it was being read. Attach it again.", "파일을 읽는 동안 내용이 변경되었습니다. 다시 첨부하세요."),
        new("Attachment.Dimensions", "Keep images under 8,192 pixels per side and 20 megapixels.", "이미지는 가로/세로 각각 8,192픽셀 이하, 총 2천만 화소 이하로 첨부하세요."),
        new("Attachment.TextLimit", "Keep each text attachment under 12,000 characters.", "텍스트 첨부 파일은 각각 12,000자 이하로 첨부하세요."),
        new("Attachment.Binary", "This file contains binary or unsupported control characters. Attach a UTF-8 or UTF-16 text file.", "지원하지 않는 제어 문자 또는 바이너리가 포함되어 있습니다. UTF-8 또는 UTF-16 텍스트 파일을 첨부하세요."),
        new("Attachment.CountLimit", "Attach up to 6 files per message.", "메시지당 최대 6개 파일을 첨부할 수 있습니다."),
        new("Attachment.TotalTextLimit", "Keep the combined text attachments under 24,000 characters.", "텍스트 첨부 파일의 합계는 24,000자 이하로 첨부하세요."),
        new("Attachment.TotalImageLimit", "Keep the combined image attachments under 12 MB.", "이미지 첨부 파일의 합계는 12 MB 이하로 첨부하세요."),
        new("Attachment.Encoding", "Save this text file as UTF-8 or UTF-16 before attaching it.", "텍스트 파일을 UTF-8 또는 UTF-16으로 저장한 후 첨부하세요."),
        new("Attachment.PngInvalid", "The file is not a valid PNG image.", "올바른 PNG 이미지 파일이 아닙니다."),
        new("Attachment.JpegInvalid", "The file is not a valid JPEG image.", "올바른 JPEG 이미지 파일이 아닙니다."),
        new("Attachment.JpegDimensions", "The JPEG dimensions could not be read. Export the image again.", "JPEG 이미지 크기를 읽을 수 없습니다. 이미지를 다시 내보내세요."),
        new("Approval.Title", "Approve TopSolid change", "TopSolid 변경 승인"),
        new("Approval.Effect", "What will change", "변경 내용"),
        new("Approval.Changes", "Requested changes", "요청한 변경"),
        new("Approval.EntireChange", "Approval applies to the entire change.", "승인은 전체 변경에 적용됩니다."),
        new("Approval.ItemNumber", "Item {0}", "항목 {0}"),
        new("Approval.NoItems", "No items", "항목 없음"),
        new("Approval.Operation", "Operation", "작업"),
        new("Approval.Parameter", "Parameter", "파라미터"),
        new("Approval.CurrentValue", "Current value", "현재 값"),
        new("Approval.NewValue", "New value", "새 값"),
        new("Approval.SiValue", "{0} {1} (SI)", "{0} {1} (SI)"),
        new("Approval.Dimensionless", "dimensionless", "무차원"),
        new("Approval.EmptyText", "Empty text", "빈 텍스트"),
        new("Approval.ValueUnavailable", "Value unavailable", "값 확인 불가"),
        new("Approval.DefinitionChange", "Formula or reference will be replaced", "수식 또는 참조 교체"),
        new("Approval.ReplacesDefinition", "This change replaces the current formula or reference with a fixed value.", "현재 수식 또는 참조를 고정 값으로 바꿉니다."),
        new("Approval.AffectedDocuments", "Affected documents", "영향받는 문서"),
        new("Approval.AllDetails", "All prepared change details", "준비된 변경 상세 보기"),
        new("Approval.Target", "Target", "대상"),
        new("Approval.Details", "Action details", "작업 상세"),
        new("Approval.Arguments", "Arguments", "인수"),
        new("Approval.Review", "Review change", "변경 검토"),
        new("Approval.Json", "Full proposal JSON", "전체 제안 JSON"),
        new("Approval.AffectedObjects", "Review the affected TopSolid objects below", "아래에서 변경할 TopSolid 객체를 검토하세요"),
        new("Approval.FullValue", "… Full value is in the Full proposal JSON tab.", "… 전체 값은 전체 제안 JSON 탭에서 확인하세요."),
        new("Approval.Tool", "Tool", "도구"),
        new("Approval.Units", "Length units", "길이 단위"),
        new("Approval.Defaults", "Defaults", "기본값"),
        new("Review.InputLengthUnits", "Input length units", "입력 길이 단위"),
        new("Review.Units", "Units", "단위"),
        new("Review.Diameter", "Diameter", "지름"),
        new("Review.Radius", "Radius", "반지름"),
        new("Review.Height", "Height", "높이"),
        new("Review.Width", "Width", "너비"),
        new("Review.Origin", "Origin", "원점"),
        new("Review.Center", "Center", "중심"),
        new("Review.AxisDirection", "Axis direction", "축 방향"),
        new("Review.Placement", "Placement", "배치"),
        new("Review.Profiles", "Profiles", "프로파일"),
        new("Review.Sketches", "Sketches", "스케치"),
        new("Review.Points", "Points", "점 목록"),
        new("Review.Method", "Method", "방법"),
        new("Review.Kind", "Kind", "종류"),
        new("Review.InputUnits", "Input units", "입력 단위"),
        new("Review.SketchPlan", "Sketch plan", "스케치 구성"),
        new("Review.CuttingConditions", "Cutting Conditions", "절삭 조건"),
        new("Review.Geometry", "Geometry", "지오메트리"),
        new("Review.Strategy", "Strategy", "전략"),
        new("Review.Comments", "Comments", "코멘트"),
        new("Review.MultiAxis", "Multi Axis", "다축"),
        new("Review.Properties", "Properties", "속성"),
        new("Review.Enum.circle", "Circle", "원"),
        new("Review.Enum.rectangle", "Rectangle", "사각형"),
        new("Review.Enum.line", "Line", "직선"),
        new("Review.Enum.arc", "Arc", "원호"),
        new("Review.Enum.polyline", "Polyline", "폴리라인"),
        new("Review.Enum.ellipse", "Ellipse", "타원"),
        new("Review.Enum.slot", "Slot", "슬롯"),
        new("Review.Enum.extrude", "Extrusion", "돌출"),
        new("Review.Enum.revolve", "Revolution", "회전"),
        new("Dev.Title", "Developer dashboard", "개발자 대시보드"),
        new("Dev.Mode", "Dev Mode", "개발자 모드"),
        new("Dev.Open", "Open dashboard", "대시보드 열기"),
        new("Dev.Description", "Model responses, MCP tools, results and elapsed time.", "모델 응답, MCP 도구, 결과 및 경과 시간을 확인합니다."),
        new("Dev.SaveLog", "Save log", "로그 저장"),
        new("Dev.SaveLogHint", "Export chat, configuration and diagnostics with API keys omitted", "API 키를 제외한 채팅, 구성 및 진단 내보내기"),
        new("Dev.Connect", "Connect MCP", "MCP 연결"),
        new("Dev.Disconnect", "Disconnect MCP", "MCP 연결 끊기"),
        new("Dev.Check", "Check TopSolid", "TopSolid 확인"),
        new("Dev.Overview", "Overview", "개요"),
        new("Dev.Responses", "Responses", "응답"),
        new("Dev.ChatResponses", "Chat responses", "채팅 응답"),
        new("Dev.Tools", "MCP tools", "MCP 도구"),
        new("Dev.Results", "Results", "결과"),
        new("Dev.Events", "Events", "이벤트"),
        new("Dev.Raw", "Raw", "원문"),
        new("Dev.Formatted", "Formatted", "서식"),
        new("Dev.Elapsed", "Elapsed time", "경과 시간"),
        new("Dev.Model", "Model time", "모델 시간"),
        new("Dev.ToolTime", "Tool time", "도구 시간"),
        new("Dev.ApprovalTime", "Approval time", "승인 대기 시간"),
        new("Dev.Search", "Search tools", "도구 검색"),
        new("Dev.Gpu", "GPU usage", "GPU 사용량"),
        new("Dev.GpuLocal", "Local computer GPUs", "로컬 컴퓨터 GPU"),
        new("Dev.GpuSampling", "Sampling GPU counters…", "GPU 카운터 수집 중…"),
        new("Dev.GpuUnavailable", "GPU counters unavailable", "GPU 카운터를 사용할 수 없음"),
        new("Dev.GpuDedicated", "Dedicated memory", "전용 메모리"),
        new("Dev.GpuShared", "Shared memory", "공유 메모리"),
        new("Dev.GpuEngine", "Busiest engine", "최대 사용 엔진"),
        new("Dev.GpuEmpty", "No GPU samples yet.", "아직 GPU 측정값이 없습니다."),
        new("Dev.GpuUnsupported", "Windows GPU counters are not available on this computer.", "이 컴퓨터에서 Windows GPU 카운터를 사용할 수 없습니다."),
        new("Dev.GpuHint", "Samples refresh every 2 seconds while this tab is open. Usage is the busiest engine per adapter; memory is current usage.", "이 탭이 열려 있으면 2초마다 갱신합니다. 사용률은 어댑터별 최대 사용 엔진, 메모리는 현재 사용량을 표시합니다."),
        new("Dev.GpuAdapter", "GPU adapter", "GPU 어댑터"),
        new("Dev.GpuLastSample", "Last sample", "최근 측정"),
        new("Dev.WindowTitle", "TopSolid Automation AI · Developer", "TopSolid Automation AI · 개발자"),
        new("Dev.TurnElapsed", "Turn elapsed", "대화 경과 시간"),
        new("Dev.WaitsHint", "Includes waits and overhead", "대기 및 처리 시간 포함"),
        new("Dev.ModelHint", "Measured completed requests", "완료된 요청 측정값"),
        new("Dev.ToolHint", "Excludes user approval wait", "사용자 승인 대기 제외"),
        new("Dev.ApprovalWait", "Approval wait", "승인 대기"),
        new("Dev.ApprovalHint", "Measured confirmation dialogs", "승인 대화 상자 측정값"),
        new("Dev.EventResults", "Events & results", "이벤트 및 결과"),
        new("Dev.FindTool", "Find tool", "도구 찾기"),
        new("Dev.FilterTools", "Filter tool names and descriptions", "도구 이름 및 설명으로 필터링"),
        new("Dev.Catalogue", "MCP catalogue", "MCP 도구 목록"),
        new("Dev.NoTurn", "No chat turn recorded", "기록된 대화 없음"),
        new("Dev.CurrentTurn", "Current turn · running", "현재 대화 · 실행 중"),
        new("Dev.LatestTurn", "Latest turn · stopped", "최근 대화 · 중지됨"),
        new("Dev.ChangeCapable", "Change-capable", "변경 가능"),
        new("Dev.ReadOnly", "Read-only", "읽기 전용"),
        new("Dev.ConnectToDiscover", "Connect MCP to discover tools.", "MCP를 연결하여 도구를 조회하세요."),
        new("Dev.NoMatchingTools", "No matching tools.", "일치하는 도구가 없습니다."),
        new("Dev.SelectEntry", "Select an entry to inspect its content.", "내용을 확인할 항목을 선택하세요."),
        new("Dev.GaugeHint", "Duration from the latest chat turn. Gauge scale: total turn elapsed time.", "최근 대화의 소요 시간입니다. 게이지 기준: 대화 전체 경과 시간."),
        new("Dev.NoDuration", "No measured duration recorded for this turn.", "이 대화의 측정된 소요 시간이 없습니다."),
        new("Dev.DashboardHint", "Gauges show measured latest-turn durations against elapsed time. Events and responses show the latest 400 retained entries; Save log exports the retained session.", "게이지는 최근 대화의 전체 경과 시간 대비 측정 시간을 표시합니다. 이벤트와 응답은 최근 400개 항목을 보여 줍니다. 로그 저장으로 보관된 세션을 내보낼 수 있습니다."),
        new("Dev.EventsCount", "{0:N0} shown · {1:N0} retained events", "{0:N0}개 표시 · 보관된 이벤트 {1:N0}개"),
        new("Dev.MessagesCount", "{0:N0} shown · {1:N0} retained messages", "{0:N0}개 표시 · 보관된 메시지 {1:N0}개"),
        new("Dev.SessionSummary", "Retained session: {0:N0} messages · {1:N0} events · {2:N0} tool calls · {3:N0} error events", "보관된 세션: 메시지 {0:N0}개 · 이벤트 {1:N0}개 · 도구 호출 {2:N0}회 · 오류 이벤트 {3:N0}개"),
        new("Dev.CatalogueCount", "{0:N0} of {1:N0} discovered tools", "조회된 도구 {1:N0}개 중 {0:N0}개"),
        new("Dialog.SaveLog", "Save TopSolid Automation diagnostic log", "TopSolid Automation 진단 로그 저장"),
        new("Dialog.LogFilter", "JSON diagnostic log (*.json)|*.json", "JSON 진단 로그 (*.json)|*.json"),
        new("Dialog.McpFilter", "MCP server executable (*.exe)|*.exe", "MCP 서버 실행 파일 (*.exe)|*.exe"),
        new("Health.Title", "Connection status", "연결 상태"),
        new("Health.Checking", "Checking connections…", "연결 확인 중…"),
        new("Health.Warning", "Connection needs attention", "연결 상태를 확인하세요"),
        new("Health.Error", "Check connection settings", "연결 설정을 확인하세요"),
        new("Health.Component.Mcp", "MCP server", "MCP 서버"),
        new("Health.Component.TopSolid", "TopSolid", "TopSolid"),
        new("Health.Component.Ai", "AI model", "AI 모델"),
        new("Health.McpChecking", "Connecting to the MCP server…", "MCP 서버에 연결하고 있습니다…"),
        new("Health.TopSolidChecking", "Connecting to TopSolid…", "TopSolid에 연결하고 있습니다…"),
        new("Health.TopSolidWaiting", "Waiting for the MCP server before checking TopSolid.", "TopSolid를 확인하기 전에 MCP 서버 연결을 기다리고 있습니다."),
        new("Health.AiChecking", "Checking the AI service and selected model…", "AI 서비스와 선택한 모델을 확인하고 있습니다…"),
        new("Health.McpReady", "The MCP server is connected.", "MCP 서버가 연결되었습니다."),
        new("Health.TopSolidReady", "TopSolid is connected and responding.", "TopSolid가 연결되어 정상적으로 응답하고 있습니다."),
        new("Health.AiReady", "The AI service is reachable and the selected model is listed.", "AI 서비스에 연결되었으며 선택한 모델이 목록에서 확인되었습니다."),
        new("Health.AiInferenceReady", "The selected AI model responded successfully.", "선택한 AI 모델이 정상적으로 응답했습니다."),
        new("Health.McpUnavailable", "Studio could not connect to its MCP server. Check the MCP server location in Developer settings, then refresh.", "MCP 서버에 연결할 수 없습니다. 개발자 설정에서 MCP 서버 위치를 확인한 후 새로 고침하세요."),
        new("Health.McpSlow", "The MCP server is taking longer than usual to connect. Wait for this check to finish, then refresh if needed.", "MCP 서버 연결이 지연되고 있습니다. 확인이 끝날 때까지 기다린 후 필요하면 새로 고침하세요."),
        new("Health.TopSolidBlocked", "TopSolid cannot be checked until the MCP server is connected.", "MCP 서버가 연결되어야 TopSolid 연결을 확인할 수 있습니다."),
        new("Health.TopSolidNotFound", "TopSolid could not be found on this computer or through the connection. Check its installation and connection setup, then refresh.", "이 PC 또는 현재 연결에서 TopSolid를 찾을 수 없습니다. 설치 상태와 연결 구성을 확인한 후 새로 고침하세요."),
        new("Health.TopSolidNotRunning", "TopSolid is installed but is not running. Open TopSolid, wait until it is ready, then refresh.", "TopSolid가 설치되어 있지만 실행 중이 아닙니다. TopSolid를 실행하고 준비가 끝나면 새로 고침하세요."),
        new("Health.TopSolidStarting", "TopSolid is not ready to accept the connection yet. It may be starting, loading a project, or waiting for a dialog. Wait until it is ready, then refresh.", "TopSolid가 아직 연결을 받을 준비가 되지 않았습니다. 시작 중이거나 프로젝트를 불러오는 중 또는 대화 상자에서 대기 중일 수 있습니다. 준비가 끝나면 새로 고침하세요."),
        new("Health.TopSolidNotResponding", "TopSolid did not respond in time. It may still be starting or busy. Check its window and wait before refreshing; your documents have not been changed by this check.", "TopSolid가 제시간에 응답하지 않았습니다. 아직 시작 중이거나 작업 중일 수 있습니다. TopSolid 창을 확인하고 잠시 기다린 후 새로 고침하세요. 이 연결 확인은 문서를 변경하지 않습니다."),
        new("Health.AiConfiguration", "The AI model is not fully configured. In Settings → AI model, choose a service and model, check the address, and enter an API key if required.", "AI 모델 설정이 완료되지 않았습니다. 설정 → AI 모델에서 서비스와 모델을 선택하고 주소 및 필요한 API 키를 확인하세요."),
        new("Health.AiChanged", "AI settings have changed. Refresh to check the new connection.", "AI 설정이 변경되었습니다. 새로 고침하여 새 연결을 확인하세요."),
        new("Health.AiNotListed", "The service responded, but the selected model was not in its model list. Check the model name or choose a listed model in AI settings.", "서비스에서 응답했지만 선택한 모델을 목록에서 확인하지 못했습니다. AI 설정에서 모델 이름을 확인하거나 목록에 있는 모델을 선택하세요."),
        new("Health.AiCatalogUnavailable", "The service's model list could not be checked. The address may be incorrect, or this service may not support model discovery. Check AI settings before retrying.", "서비스의 모델 목록을 확인할 수 없습니다. 주소가 잘못되었거나 모델 목록 조회를 지원하지 않는 서비스일 수 있습니다. AI 설정을 확인한 후 다시 시도하세요."),
        new("Health.AiUnavailable", "The selected model or service address could not be found. Check the address and choose an available model in AI settings.", "선택한 모델 또는 서비스 주소를 찾을 수 없습니다. AI 설정에서 주소를 확인하고 사용 가능한 모델을 선택하세요."),
        new("Health.AiAuthentication", "The AI service did not accept the credentials or account permissions. Check the API key and model access in AI settings.", "AI 서비스에서 인증 정보 또는 계정 권한을 확인하지 못했습니다. AI 설정에서 API 키와 모델 사용 권한을 확인하세요."),
        new("Health.AiLimit", "The AI service reported a usage or request limit. Wait for the limit to reset, or check your provider's quota. Refreshing the model list does not confirm that chat quota has recovered.", "AI 서비스의 사용량 또는 요청 한도에 도달했습니다. 한도가 초기화될 때까지 기다리거나 서비스 제공자의 할당량을 확인하세요. 모델 목록 새로 고침만으로 채팅 한도 복구를 확인할 수는 없습니다."),
        new("Health.AiPending", "The AI model is processing a request. Please wait; a local model may need time to load.", "AI 모델이 요청을 처리하고 있습니다. 잠시 기다려 주세요. 로컬 모델을 불러오는 데 시간이 걸릴 수 있습니다."),
        new("Health.AiSlow", "The AI service is taking longer than expected or the check timed out. It may be busy or loading a model. Wait, check the service, then refresh. A running chat can be cancelled from the chat area.", "AI 서비스 응답이 지연되거나 연결 확인 시간이 초과되었습니다. 서비스가 사용 중이거나 모델을 불러오는 중일 수 있습니다. 잠시 기다린 후 서비스를 확인하고 새로 고침하세요. 진행 중인 채팅은 채팅 입력 영역에서 취소할 수 있습니다."),
        new("Health.AiNetwork", "The AI service could not be reached. Check the network and service address; for a local model, check that its server is running.", "AI 서비스에 연결할 수 없습니다. 네트워크와 서비스 주소를 확인하세요. 로컬 모델인 경우 서버가 실행 중인지 확인하세요."),
        new("Health.AiTemporary", "The AI service is temporarily unavailable or busy. Wait a moment and refresh.", "AI 서비스를 일시적으로 사용할 수 없거나 서비스가 사용 중입니다. 잠시 기다린 후 새로 고침하세요."),
        new("Health.AiFailure", "The AI service returned an unexpected response. Check the selected service and model, then refresh. Technical details are available in Dev Mode.", "AI 서비스에서 예상하지 못한 응답을 받았습니다. 선택한 서비스와 모델을 확인한 후 새로 고침하세요. 기술 정보는 개발자 모드에서 확인할 수 있습니다."),
        new("Health.Cancelled", "The connection check was cancelled. Refresh when you are ready.", "연결 확인이 취소되었습니다. 준비되면 새로 고침하세요."),
        new("Health.VerificationNote", "Connection checks do not send a chat request or change CAD documents. Model availability does not guarantee inference quota.", "연결 확인은 채팅 요청을 전송하거나 CAD 문서를 변경하지 않습니다. 모델 목록에 표시되어도 AI 응답 할당량은 별도로 제한될 수 있습니다."),
        new("Health.WaitNote", "A request is still running. You can close this dialog with Cancel. Refresh becomes available when the request finishes.", "요청이 진행 중입니다. 취소를 눌러 이 대화 상자를 닫을 수 있습니다. 요청이 끝나면 새로 고침할 수 있습니다."),
        new("Health.NotConfigured", "not configured", "설정 필요"),
    ];

    private static readonly IReadOnlyDictionary<string, Entry> ByKey = Entries.ToDictionary(e => e.Key, StringComparer.Ordinal);
    private static readonly IReadOnlyDictionary<string, Entry> ByEnglish = Entries.GroupBy(e => e.English, StringComparer.Ordinal).ToDictionary(g => g.Key, g => g.First(), StringComparer.Ordinal);
    private static readonly List<WeakReference<Window>> StandaloneWindows = [];
    public static string CurrentLanguage { get; private set; } = "en";
    public static event Action? Changed;
    public static IReadOnlyCollection<string> Keys => ByKey.Keys.ToArray();

    public static string Normalize(string? language) => language?.Trim().ToLowerInvariant() switch { "en" => "en", "ko" => "ko", _ => "system" };

    public static void Apply(string? language)
    {
        var app = Application.Current;
        if (app != null && !app.Dispatcher.CheckAccess()) { app.Dispatcher.Invoke(() => Apply(language)); return; }
        CurrentLanguage = Normalize(language) switch { "en" => "en", "ko" => "ko", _ => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "ko" ? "ko" : "en" };
        if (app != null)
            foreach (var entry in Entries) app.Resources["Ui." + entry.Key] = Value(entry);
        WeakReference<Window>[] windows;
        lock (StandaloneWindows) { StandaloneWindows.RemoveAll(reference => !reference.TryGetTarget(out _)); windows = StandaloneWindows.ToArray(); }
        foreach (var reference in windows)
            if (reference.TryGetTarget(out var window) && !window.Dispatcher.HasShutdownStarted)
            {
                if (window.Dispatcher.CheckAccess()) Publish(window);
                else window.Dispatcher.BeginInvoke(new Action(() => Publish(window)));
            }
        Changed?.Invoke();
    }

    public static void InitializeResources(Window window)
    {
        ArgumentNullException.ThrowIfNull(window);
        if (Application.Current is { } app)
        {
            void PublishMissing()
            {
                foreach (var entry in Entries)
                    if (!app.Resources.Contains("Ui." + entry.Key)) app.Resources["Ui." + entry.Key] = Value(entry);
            }
            if (app.Dispatcher.CheckAccess()) PublishMissing();
            else app.Dispatcher.Invoke(PublishMissing);
            return;
        }
        if (!window.Dispatcher.CheckAccess()) { window.Dispatcher.Invoke(() => InitializeResources(window)); return; }
        Publish(window);
        WeakReference<Window> reference;
        lock (StandaloneWindows)
        {
            StandaloneWindows.RemoveAll(existing => !existing.TryGetTarget(out _));
            if (StandaloneWindows.Any(existing => existing.TryGetTarget(out var target) && ReferenceEquals(target, window))) return;
            reference = new WeakReference<Window>(window);
            StandaloneWindows.Add(reference);
        }
        window.Closed += (_, _) => { lock (StandaloneWindows) StandaloneWindows.Remove(reference); };
    }

    private static void Publish(Window window)
    { foreach (var entry in Entries) window.Resources["Ui." + entry.Key] = Value(entry); }

    public static string Get(string key, params object[] args)
    {
        var text = ByKey.TryGetValue(key, out var entry) ? Value(entry) : key;
        return args.Length == 0 ? text : string.Format(CurrentLanguage == "ko" ? CultureInfo.GetCultureInfo("ko-KR") : CultureInfo.GetCultureInfo("en-US"), text, args);
    }

    /// <summary>Localizes an exact Studio-owned English label; unmatched external text is returned verbatim.</summary>
    public static string Text(string nativeEnglish) => ByEnglish.TryGetValue(nativeEnglish, out var entry) ? Value(entry) : nativeEnglish;
    public static string? KeyForText(string nativeEnglish) => ByEnglish.TryGetValue(nativeEnglish, out var entry) ? entry.Key : null;
    private static string Value(Entry entry) => CurrentLanguage == "ko" && !string.IsNullOrEmpty(entry.Korean) ? entry.Korean : entry.English;
}
