// Generated from the reviewed allowlist in scripts/ApiReference/generate_read_tools.py.
// Each call is compiled against the matched 7.20 SDK. No generic API invocation.
using System;
using Newtonsoft.Json.Linq;
using TopSolid.Automation.Mcp.Server.AddIn.Automation;
using TopSolid.Kernel.Automating;
using TopSolid.Cad.Design.Automating;
using TopSolid.Cad.Drafting.Automating;
using TopSolid.Cad.Electrode.Automating;
using TopSolid.Cam.NC.Kernel.Automating;
using TopSolid.Cae.Kernel.Automating;

namespace TopSolid.Automation.Mcp.Server.AddIn.Tools
{
    internal static class PdmReadTools
    {
        public static void Register(AutomationGateway a, Action<ToolDefinition> register)
        {
            register(new ToolDefinition("topsolid_list_projects", "List working projects with friendly name and pdmObjectId in each item. Names are included; do not fetch each object again. Use limit=100 and follow hasMore with offset to list all. Libraries have a separate tool. Names only by default. Set includeCreationDates=true only when dates are requested; unavailable dates are explicit. Never group or omit rows.", Schema.Page(new JObject { ["includeCreationDates"] = Schema.Boolean("Optional, default false. Query creation dates only when requested."), ["orderBy"] = Schema.Choice("Optional global name or creation-date order before pagination. Name ordering needs no dates. Missing dates block chronological ordering.", "oldestFirst", "newestFirst", "nameAscending", "nameDescending") }, 100),
                p => a.Read("kernel", () => a.ListPdmProjects(true, p)), "Pdm", new string[0], true, new[] { "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IPdm.GetProjects.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IPdm.GetName.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IDocuments.GetDocument.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IDocuments.Exists.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IDocuments.GetPdmObject.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IParameters.GetCreationDateParameter.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IParameters.GetDateTimeValue.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IParameters.GetParameterType.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IElements.Exists.html" }));
            register(new ToolDefinition("topsolid_list_libraries", "List library projects with friendly name and pdmObjectId in each item. Names are included; do not fetch each object again. Use limit=100 and follow hasMore with offset to list all. Names only by default. Set includeCreationDates=true only when dates are requested; unavailable dates are explicit. Never group or omit rows.", Schema.Page(new JObject { ["includeCreationDates"] = Schema.Boolean("Optional, default false. Query creation dates only when requested."), ["orderBy"] = Schema.Choice("Optional global name or creation-date order before pagination. Name ordering needs no dates. Missing dates block chronological ordering.", "oldestFirst", "newestFirst", "nameAscending", "nameDescending") }, 100),
                p => a.Read("kernel", () => a.ListPdmProjects(false, p)), "Pdm", new string[0], true, new[] { "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IPdm.GetProjects.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IPdm.GetName.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IDocuments.GetDocument.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IDocuments.Exists.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IDocuments.GetPdmObject.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IParameters.GetCreationDateParameter.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IParameters.GetDateTimeValue.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IParameters.GetParameterType.html", "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IElements.Exists.html" }));
            register(new ToolDefinition("topsolid_get_current_project", "Get current project.", new JObject(),
                p => a.Read("kernel", () => AutomationValues.Result(TopSolidHost.Pdm.GetCurrentProject())), "Pdm", new string[0], true, new[] { "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IPdm.GetCurrentProject.html" }));
            register(new ToolDefinition("topsolid_get_selected_pdm_objects", "Get selected pdm objects.", Schema.Page(new JObject()),
                p => a.Read("kernel", () => AutomationValues.Page(TopSolidHost.Pdm.GetSelectedPdmObjectIds(), p)), "Pdm", new string[0], true, new[] { "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IPdm.GetSelectedPdmObjectIds.html" }));
            register(new ToolDefinition("topsolid_search_projects", "Search projects.", Schema.Page(new JObject { ["name"] = Schema.Text("Exact search name.", 256) }),
                p => a.Read("kernel", () => AutomationValues.Page(TopSolidHost.Pdm.SearchProjectByName((string)p["name"]), p)), "Pdm", new[] { "name" }, true, new[] { "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IPdm.SearchProjectByName.html" }));
            register(new ToolDefinition("topsolid_search_documents", "Search documents.", Schema.Page(new JObject { ["pdmObjectId"] = Schema.Text("Working or library project PdmObjectId to search, not a folder ID."), ["name"] = Schema.Text("Exact document name.",256) }),
                p => a.Read("kernel", () => AutomationValues.Page(TopSolidHost.Pdm.SearchDocumentByName(a.Pdm(p), (string)p["name"]), p)), "Pdm", new[] { "pdmObjectId", "name" }, true, new[] { "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IPdm.SearchDocumentByName.html" }));
            register(new ToolDefinition("topsolid_list_major_revisions", "List major revisions.", Schema.Page(new JObject { ["pdmObjectId"] = Schema.Text("PDM object ID returned by a tool.") }),
                p => a.Read("kernel", () => AutomationValues.Page(TopSolidHost.Pdm.GetMajorRevisions(a.Pdm(p)), p)), "Pdm", new[] { "pdmObjectId" }, true, new[] { "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IPdm.GetMajorRevisions.html" }));
            register(new ToolDefinition("topsolid_list_minor_revisions", "List minor revisions.", Schema.Page(new JObject { ["majorRevisionId"] = Schema.Text("Major revision ID returned by a tool.") }),
                p => a.Read("kernel", () => AutomationValues.Page(TopSolidHost.Pdm.GetMinorRevisions(new PdmMajorRevisionId((string)p["majorRevisionId"])), p)), "Pdm", new[] { "majorRevisionId" }, true, new[] { "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IPdm.GetMinorRevisions.html" }));
            register(new ToolDefinition("topsolid_resolve_pdm_document", "Resolve pdm document.", new JObject { ["pdmObjectId"] = Schema.Text("PDM object ID returned by a tool.") },
                p => a.Read("kernel", () => AutomationValues.Result(TopSolidHost.Documents.GetDocument(a.Pdm(p)))), "Pdm", new[] { "pdmObjectId" }, true, new[] { "https://help.topsolid.com/7.20/en/TopSolid'Automation/api/kernel/TopSolid.Kernel.Automating.IDocuments.GetDocument.html" }));
        }
    }
}
